name: Build pull request

on:
  push: 
  workflow_dispatch:

jobs:
  build-pull-request:
    name: Build pull request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0
      - name: Setup node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 20.12.2
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build app
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: preview
          path: dist
